# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      # Runs on every weekday, Monday to Friday.
      interval: "daily"
      time: "19:00"
      timezone: "Europe/Amsterdam"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 10
    versioning-strategy: "lockfile-only"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
