require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 125

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
